const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Argentina",
      price: 100,
      image: require("./images/argentina.png"),
      category: "Remesas",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Estados Unidos",
      price: 100,
      image: require("./images/estados-unidos.png"),
      category: "Remesas",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Venezuela",
      price: 475,
      image: require("./images/venezuela.png"),
      category: "Remesas",
      img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325289&w=1000",
      cantidad: 1,
    },
    {
      id: 4,
      title: "España",
      price: 180,
      image: require("./images/espana.png"),
      category: "Remesas",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Canada",
      price: 150,
      image: require("./images/canada.png"),
      category: "Remesas",
      img1: " https://stockx-360.imgix.net/Nike-Dunk-Low-SP-Kentucky/Images/Nike-Dunk-Low-SP-Kentucky/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
      cantidad: 1,
    },
    {
      id: 6,
      title: "Brasil",
      price: 200,
      image: require("./images/brasil.png"),
      category: "Remesas",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-University-Red/Images/Nike-Dunk-Low-Off-White-University-Red/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321824&w=1000",
      cantidad: 1,
    },
  ],
};

export default data;
